//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public long Id { get; set; }
        public Nullable<long> Type { get; set; }
        public string Selector { get; set; }
        public string Value { get; set; }
        public long TaskId { get; set; }
    }
}
