//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public string Answer { get; set; }
    }
}
